sudo: required

language: nix

services:
  - docker

git:
  quiet: true

jobs:
  include:

    - stage: Tests
      name: Behaviour Tests
      script: ./scripts/test.sh

    - stage: Nix
      name: Nix Package
      script: nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
